# Generated by Django 5.2 on 2025-08-04 15:59

import clickhouse_backend.models
import django.db.models.manager
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('symbol', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('headline', clickhouse_backend.models.StringField()),
                ('sentiment', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('impact_score', clickhouse_backend.models.Float64Field(default=0.0)),
                ('timestamp', clickhouse_backend.models.DateTime64Field(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'engine': clickhouse_backend.models.MergeTree(index_granularity=8192, order_by=('symbol', 'timestamp'), partition_by=clickhouse_backend.models.toYYYYMM('timestamp'), primary_key=('symbol', 'timestamp')),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OHLCData',
            fields=[
                ('id', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('symbol', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('open', clickhouse_backend.models.Float64Field()),
                ('high', clickhouse_backend.models.Float64Field()),
                ('low', clickhouse_backend.models.Float64Field()),
                ('close', clickhouse_backend.models.Float64Field()),
                ('timestamp', clickhouse_backend.models.DateTime64Field(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'engine': clickhouse_backend.models.MergeTree(index_granularity=8192, order_by=('symbol', 'timestamp'), partition_by=clickhouse_backend.models.toYYYYMM('timestamp'), primary_key=('symbol', 'timestamp')),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OptionData',
            fields=[
                ('id', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('symbol', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('expiry_date', clickhouse_backend.models.DateField()),
                ('strike_price', clickhouse_backend.models.Float64Field()),
                ('call_put', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('implied_volatility', clickhouse_backend.models.Float64Field()),
                ('volume', clickhouse_backend.models.Int32Field()),
                ('timestamp', clickhouse_backend.models.DateTime64Field(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'engine': clickhouse_backend.models.MergeTree(index_granularity=8192, order_by=('symbol', 'expiry_date', 'timestamp'), partition_by=clickhouse_backend.models.toYYYYMM('expiry_date'), primary_key=('symbol', 'expiry_date')),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
